# Generated by Django 5.2.8 on 2026-01-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_resumeitem_category_alter_resumeitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
