# Generated by Django 5.2.8 on 2026-01-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_resumeitem_category_alter_resumeitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
