# Generated by Django 5.2.8 on 2026-01-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_category_alter_resumeitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
