# Generated by Django 5.2.8 on 2026-02-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/covers/'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='resume/images/'),
        ),
    ]
