# Generated by Django 5.2.8 on 2026-02-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_cover_image_resumeitem_uploaded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
