# Generated by Django 5.2.8 on 2026-05-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_projectimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMePP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
