# Generated by Django 5.2.8 on 2026-07-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_aboutmepp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
