# Generated by Django 5.2.8 on 2026-07-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_project_options_project_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/details/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
