# Generated by Django 5.2.8 on 2026-07-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_projectimage_uploaded_image_alter_projectimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/hero/')),
                ('alt_text', models.CharField(default='Hiking in the mountains', max_length=200)),
            ],
            options={
                'verbose_name': 'about me hero image',
                'verbose_name_plural': 'about me hero image',
            },
        ),
    ]
