# Generated by Codex on 2026-07-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_aboutmehero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="resumeitem",
            name="image",
        ),
    ]
