# Generated by Django on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_remove_static_image_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeProfileImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="home/profile/")),
                (
                    "alt_text",
                    models.CharField(
                        default="Portrait of Dominik Ivacic",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "home profile image",
                "verbose_name_plural": "home profile image",
            },
        ),
    ]
